apiVersion: apps/v1
kind: Deployment
metadata:
  name: appoint-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appoint
          image: usmankamalworld/appointments
          ports:
            - containerPort: 7070
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /appointments
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /appointments
              port: 7070
            initialDelaySeconds: 6
            periodSeconds: 6
---
apiVersion: v1
kind: Service
metadata:
  name: appoint-serv
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
