apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: usmankamalworld/frontend
          ports:
            - containerPort: 3000
          env:
            - name: DOCTORS_SERVICE_URL
              value: "10.109.205.92:9090" 
            - name: APPOINTMENTS_SERVICE_URL
              value: "10.100.166.207:7070"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /hello
              port: 3000
            initialDelaySeconds: 7
            periodSeconds: 7
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-serv
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
