apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: usmankamalworld/doctors
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /doctors
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /doctors
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5            
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-serv
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
