name: CI/CD Pipeline for Appointments

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'appointments/**'
  push:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        DOCKER_VERSION=$(git rev-parse --short HEAD)
        APPOINTMENT_VERSION=${DOCKER_VERSION}
        echo "APPOINTMENT_VERSION=${APPOINTMENT_VERSION}" >> $GITHUB_ENV        
        docker build -t ${{ secrets.DOCKER_USERNAME }}/appointments:${DOCKER_VERSION} ./appointments
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/appointments:${DOCKER_VERSION}
        
    - name: Update .env file with APPOINTMENT_VERSION
      run: echo "APPOINTMENT_VERSION=${APPOINTMENT_VERSION}" >> .env
